### Eureka Client 配置文件
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13131/eureka/
### 允许采用 bean 名字进行重写定义
spring:
  main:
    allow-bean-definition-overriding: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
#ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000